#!/usr/bin/env python3
"""
Generate publication-quality figures for "Underpaid to Measure?" paper.

Figures:
  1. NSC sensitivity diagram (revised Figure 1)
  2. Digit heaping by month (generated by digit_heaping.py)
  3. Last digit distribution (generated by digit_heaping.py)
  4. Allometric residual patterns (generated by allometric_residuals.py)

This script generates Figure 1 (NSC sensitivity). The empirical figures
are generated by their respective analysis scripts.

All figures designed for grayscale compatibility.

Usage:
    python figures.py
"""

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np

FIG_DIR = Path(__file__).parent.parent / "figures"

# Matplotlib defaults for publication quality
plt.rcParams.update({
    "font.family": "serif",
    "font.size": 11,
    "axes.labelsize": 13,
    "axes.titlesize": 12,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "legend.fontsize": 9,
    "figure.dpi": 300,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
})


def nsc_wage(w_bar, e_bar, q, r, b):
    """Compute the no-shirking condition critical wage."""
    return w_bar + e_bar + (e_bar / q) * (r + b)


def figure1_nsc_sensitivity():
    """
    Figure 1: NSC sensitivity to detection probability (q) and outside option (w̄).

    Shows how the critical wage varies with detection probability for different
    outside option levels. Horizontal lines show GS-4 and GS-6 wages.
    """
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5))

    # Panel A: NSC vs detection probability q
    ax = axes[0]

    q_range = np.linspace(0.002, 0.05, 100)

    # Central parameters
    e_bar = 4.32  # effort cost $/hr (0.25 × GS-4 $17.27)
    r = 0.004  # monthly discount rate (~5% annual)
    b = 0.02   # monthly separation rate

    # Different outside options
    w_bars = [14.0, 16.0, 18.0, 20.0]
    linestyles = ["-", "--", "-.", ":"]
    markers = ["o", "s", "^", "D"]

    for w_bar, ls, mk in zip(w_bars, linestyles, markers):
        w_star = nsc_wage(w_bar, e_bar, q_range, r, b)
        ax.plot(q_range, w_star, color="black", linestyle=ls,
                label=f"w̄ = ${w_bar:.0f}/hr", linewidth=1.2)

    # GS wage lines (2025 RUS locality pay, OPM)
    ax.axhline(y=17.27, color="0.6", linestyle="-", linewidth=2, alpha=0.7)
    ax.text(0.042, 17.42, "GS-4", fontsize=12, color="0.5", fontweight="bold")
    ax.axhline(y=19.33, color="0.45", linestyle="-", linewidth=2, alpha=0.7)
    ax.text(0.042, 19.48, "GS-5", fontsize=12, color="0.4", fontweight="bold")
    ax.axhline(y=21.54, color="0.3", linestyle="-", linewidth=2, alpha=0.7)
    ax.text(0.042, 21.69, "GS-6", fontsize=12, color="0.3", fontweight="bold")

    # FIA QA rate: stated 4%/year ≈ 0.003/month; 0.04 if applied monthly
    ax.axvline(x=0.003, color="0.5", linestyle=":", alpha=0.8, linewidth=1.2)
    ax.text(0.0035, ax.get_ylim()[0] + 1, "FIA QA\n(monthly\nequiv.)",
            fontsize=10, color="0.45")
    ax.axvline(x=0.04, color="0.7", linestyle=":", alpha=0.6, linewidth=0.8)
    ax.text(0.0405, ax.get_ylim()[0] + 1, "q = 0.04\n(optimistic)",
            fontsize=10, color="0.55")

    ax.set_xlabel("Detection Probability (q)")
    ax.set_ylabel("Critical Wage w* ($/hr)")
    ax.set_title("(a) NSC vs. Detection Probability")
    ax.legend(loc="upper right", fontsize=8)
    ax.set_xlim(0.002, 0.05)
    ax.set_ylim(15, 80)
    ax.grid(True, alpha=0.3)

    # Panel B: NSC vs effort cost
    ax = axes[1]

    e_range = np.linspace(1.0, 8.0, 100)
    q_values = [0.01, 0.02, 0.03, 0.04]

    w_bar_central = 16.0

    for q, ls in zip(q_values, linestyles):
        w_star = nsc_wage(w_bar_central, e_range, q, r, b)
        ax.plot(e_range, w_star, color="black", linestyle=ls,
                label=f"q = {q:.2f}", linewidth=1.2)

    # GS wage lines (2025 RUS locality pay, OPM)
    ax.axhline(y=17.27, color="0.6", linestyle="-", linewidth=2, alpha=0.7)
    ax.text(7.2, 17.42, "GS-4", fontsize=12, color="0.5", fontweight="bold")
    ax.axhline(y=19.33, color="0.45", linestyle="-", linewidth=2, alpha=0.7)
    ax.text(7.2, 19.48, "GS-5", fontsize=12, color="0.4", fontweight="bold")
    ax.axhline(y=21.54, color="0.3", linestyle="-", linewidth=2, alpha=0.7)
    ax.text(7.2, 21.69, "GS-6", fontsize=12, color="0.3", fontweight="bold")

    ax.set_xlabel("Effort Cost ē ($/hr)")
    ax.set_ylabel("Critical Wage w* ($/hr)")
    ax.set_title("(b) NSC vs. Effort Cost")
    ax.legend(loc="upper left", fontsize=8)
    ax.set_xlim(1, 8)
    ax.set_ylim(15, 80)
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    fig.savefig(FIG_DIR / "figure1_nsc_sensitivity.pdf")
    fig.savefig(FIG_DIR / "figure1_nsc_sensitivity.png")
    print(f"Saved: {FIG_DIR / 'figure1_nsc_sensitivity.pdf'}")
    plt.close(fig)


def figure1_cross_state_nsc():
    """
    Supplementary figure: Cross-state NSC variation using BLS wage data.
    Shows how the outside option varies by state/region and its effect on NSC.
    """
    # BLS OES approximate median hourly wages for competing occupations (2023)
    # Sources: BLS 37-3011 (Landscaping), 45-4021 (Logging), 41-2031 (Retail)
    state_data = {
        "VT": {"landscaping": 16.50, "logging": 19.00, "retail": 14.50},
        "ME": {"landscaping": 16.00, "logging": 18.50, "retail": 14.00},
        "MN": {"landscaping": 17.50, "logging": 20.00, "retail": 15.00},
        "WI": {"landscaping": 16.00, "logging": 18.00, "retail": 14.50},
        "GA": {"landscaping": 15.00, "logging": 17.00, "retail": 13.50},
        "CO": {"landscaping": 18.00, "logging": 20.50, "retail": 16.00},
        "OR": {"landscaping": 17.50, "logging": 21.00, "retail": 15.50},
        "WA": {"landscaping": 19.00, "logging": 22.00, "retail": 16.50},
    }

    fig, ax = plt.subplots(figsize=(8, 5))

    states = sorted(state_data.keys())
    x = np.arange(len(states))
    width = 0.25

    landscaping = [state_data[s]["landscaping"] for s in states]
    logging_w = [state_data[s]["logging"] for s in states]
    retail = [state_data[s]["retail"] for s in states]

    ax.bar(x - width, retail, width, color="0.8", edgecolor="black",
           linewidth=0.5, label="Retail")
    ax.bar(x, landscaping, width, color="0.5", edgecolor="black",
           linewidth=0.5, label="Landscaping")
    ax.bar(x + width, logging_w, width, color="0.3", edgecolor="black",
           linewidth=0.5, label="Logging")

    ax.axhline(y=17.27, color="0.5", linestyle="--", linewidth=1.5, label="GS-4")
    ax.axhline(y=19.33, color="0.4", linestyle="-.", linewidth=1.5, label="GS-5")
    ax.axhline(y=21.54, color="0.2", linestyle=":", linewidth=1.5, label="GS-6")

    ax.set_xlabel("State")
    ax.set_ylabel("Median Hourly Wage ($)")
    ax.set_title("Outside Option Wages by State vs. GS Pay Grades")
    ax.set_xticks(x)
    ax.set_xticklabels(states)
    ax.legend(fontsize=8, loc="upper left")
    ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
    fig.savefig(FIG_DIR / "cross_state_wages.pdf")
    fig.savefig(FIG_DIR / "cross_state_wages.png")
    print(f"Saved: {FIG_DIR / 'cross_state_wages.pdf'}")
    plt.close(fig)


def main():
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    print("Generating publication figures...")
    print()

    figure1_nsc_sensitivity()
    figure1_cross_state_nsc()

    print("\nAll figures generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
